// Vendors the Lucide icons folio uses into src/icons.ts (no runtime dependency).
// Usage: node scripts/gen-icons.mjs   (edit ICONS or VERSION, then rerun)
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const VERSION = '1.50.0'

/** folio icon name -> Lucide icon name (https://lucide.dev/icons). */
const ICONS = {
  back: 'chevron-left',
  select: 'mouse-pointer-2',
  lasso: 'lasso',
  pen: 'pencil',
  highlighter: 'highlighter',
  eraser: 'eraser',
  shape: 'shapes',
  rectangle: 'square',
  ellipse: 'circle',
  triangle: 'triangle',
  diamond: 'diamond',
  line: 'slash',
  arrow: 'move-up-right',
  text: 'type',
  undo: 'undo-2',
  redo: 'redo-2',
  plus: 'plus',
  minus: 'minus',
  trash: 'trash-2',
  copy: 'copy',
  more: 'ellipsis',
  search: 'search',
  settings: 'settings',
  sliders: 'sliders-horizontal',
  folder: 'folder',
  notebook: 'file',
  doc: 'file-text',
  download: 'download',
  upload: 'upload',
  sparkles: 'sparkles',
  layers: 'layers',
  cleanup: 'scan-text',
  tidy: 'text-align-justify',
  restore: 'signature',
  'copy-text': 'clipboard-type',
  'frame-content': 'square-dashed-mouse-pointer',
  unframe: 'square-dashed',
  group: 'group',
  ungroup: 'ungroup',
  front: 'bring-to-front',
  back_: 'send-to-back',
  check: 'check',
  x: 'x',
  up: 'chevron-up',
  down: 'chevron-down',
  right: 'chevron-right',
  chevleft: 'chevron-left',
  user: 'user',
  cloud: 'cloud',
  fit: 'scan',
  fullscreen: 'maximize',
  edit: 'square-pen',
  tag: 'tag',
  move: 'folder-input',
  sort: 'arrow-up-down',
  offline: 'wifi-off',
  alert: 'triangle-alert',
  eyedropper: 'pipette',
  zen: 'leaf',
  presenter: 'presentation',
  menu: 'menu',
  hand: 'hand',
  frame: 'frame',
  blur: 'droplet',
  note: 'message-square-text',
  counter: 'map-pin',
  image: 'image',
  lock: 'lock',
  unlock: 'lock-open',
  grid: 'grid-3x3',
  library: 'library',
  keyboard: 'keyboard',
  paste: 'clipboard-paste',
  compact: 'eye-off',
  'align-left': 'align-start-vertical',
  'align-center-x': 'align-center-vertical',
  'align-right': 'align-end-vertical',
  'align-top': 'align-start-horizontal',
  'align-center-y': 'align-center-horizontal',
  'align-bottom': 'align-end-horizontal',
  'distribute-x': 'align-horizontal-distribute-center',
  'distribute-y': 'align-vertical-distribute-center',
}

/** Child elements of a Lucide SVG as [tag, attributes] pairs. */
function nodes(svg) {
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '')
  return [...body.matchAll(/<(\w+)([^>]*?)\/?>/g)].map(([, tag, attrs]) => [
    tag,
    Object.fromEntries([...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(([, k, v]) => [k, v])),
  ])
}

const entries = await Promise.all(Object.entries(ICONS).map(async ([name, lucide]) => {
  const res = await fetch(`https://unpkg.com/lucide-static@${VERSION}/icons/${lucide}.svg`)
  if (!res.ok) throw new Error(`${lucide}: HTTP ${res.status}`)
  return `  ${JSON.stringify(name)}: ${JSON.stringify(nodes(await res.text()))},`
}))

const out = `// Generated by scripts/gen-icons.mjs from lucide-static@${VERSION} (ISC license). Do not edit.

export type IconNode = readonly (readonly [tag: string, attrs: Readonly<Record<string, string>>])[]

export const ICONS = {
${entries.join('\n')}
} as const satisfies Record<string, IconNode>

export type IconName = keyof typeof ICONS
`
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'icons.ts'), out)
console.log(`wrote ${entries.length} icons`)
